apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Namespace }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  linodeCliToken: {{ .Values.image.env.linodeCliToken | b64enc }}
  linodeCliObjAccessKey: {{ .Values.image.env.linodeCliObjAccessKey | b64enc }}
  linodeCliObjSecretKey: {{ .Values.image.env.linodeCliObjSecretKey | b64enc }}
  dbPass: {{ .Values.image.env.dbPass | b64enc }}